language: generic
sudo: required
services:
- docker
script:
- docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/build.sh armhf"
before_deploy:
- .travis/decrypt.sh
deploy:
- provider: releases
  skip_cleanup: true
  file: "*.snap"
  file_glob: true
  api_key:
    secure: O1aedO8zCOjWchGLVNami7uGtHnYp5iecEPd3/TaarsE+3FTjKpWvao+sCv7wfHeBB7jFWx+xnl06hJLRFJDwd9idh/lispXTXXD4P+JVV887HA05ljHwsUwGDeK4uhT7bYHkY6Xd0IP6ygdn1cQB/Zec0GpLMpLEjoUTkXMhjiY8K7gfVkiZZF5VoA8zbrp/+8/rk56hpYInvtw7RcVC8zeZrsJ4z0EN+vNHcKQjoKaLz6fSq5I3v8DsC/JPr7u1zwfkH+ofGz/s4dMpka5Ul/DS3viHoI1RvCdxBVwwoOGKj7sXT5YNQFyAjEALy6PHTvjqGgjbx7nCQ5dnuJ7wE7MKnLyoeiLoUrgTPVrm97/x2HmuQGLwFslVCkVfoN157nTtUW0fQzeRKnA+wWalCScii/VFTB+lUawpwmaRiCqaufsb7PKbu9hqXI8muzslyVUs2S6a+IVYF3c8yCXeY+4FGH61lM92oxbNk5YyJJ+GIxC2qu4R9yj/q30Pl+K8VFUwul+xStsFBUBb6pgTdhLtFxSMSIbmTHTXdYcEOMaWCf+60OybRtD9If8hnYpIBnExPDBW7e6fqkgvHvtmJErpNG0li4khVNDsHgZfiEGDKjke67gD62CAHZmOrKl2WVnOC1IYs0BqBqN6VAJRJGZIfG3eXx/g3Ixx3GTqGU=
  on:
    repo: fuzeman/nanopi-neo-air-kernel
    tags: true
- provider: script
  skip_cleanup: true
  script:
  - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh $TRAVIS_TAG"
  on:
    repo: fuzeman/nanopi-neo-air-kernel
    tags: true
#- provider: script
#  skip_cleanup: true
#  script:
#  - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh"
#  on:
#    repo: fuzeman/nanopi-neo-air-kernel
#    branch: master
