name: nanopi-neo-air-kernel
summary: Minimal kernel for the NanoPi NEO Air
version: 4.10.8-alpha.2
type: kernel

description: |
  Kernel for the NanoPi NEO Air with the bare minimum drivers and modules.

  See https://github.com/fuzeman/nanopi-neo-air-kernel for details.

architectures: [armhf]
confinement: strict
grade: devel

parts:
    kernel:
        plugin: fm-kernel

        source: https://github.com/fuzeman/linux-ubuntu-zesty.git
        source-commit: 9f381a210844b482b9100e3e4b5e850310d0d35f
        source-depth: 1
        source-type: git

        build-packages: [bc, cpio, kmod, libssl-dev]

        kdefconfig: ['--makefile=debian/snapcraft.mk', 'branch=sunxi','flavour=nanopi-neo-air', 'config']
        kernel-image-target: zImage

        kconfigs:
          - CONFIG_LOCALVERSION="-nanopi-neo-air"
          - CONFIG_SQUASHFS=m
          - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y

        kernel-initrd-modules:
          - squashfs

        kernel-device-trees:
          - sun8i-h3-nanopi-neo

        prepare: |
          touch .scmversion
